BEGIN;

DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS show;

COMMIT;

BEGIN;

CREATE TABLE "user" (
  user_id SERIAL UNIQUE PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE product (
  product_id SERIAL UNIQUE PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price VARCHAR(10) NOT NULL,
  sku VARCHAR(30) NOT NULL,
  category VARCHAR(100) NOT NULL,
  main_img VARCHAR(100) NOT NULL,
  sup_img_1 VARCHAR(100),
  sup_img_2 VARCHAR(100),
  sup_img_3 VARCHAR(100),
  sold BOOLEAN,
  product_position VARCHAR(10)
);

CREATE TABLE show (
  show_id SERIAL UNIQUE PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  show_date VARCHAR(100) NOT NULL,
  date_literal VARCHAR NOT NULL,
  venue VARCHAR(100) NOT NULL,
  location VARCHAR(100) NOT NULL,
  website VARCHAR(100) NOT NULL,
  current BOOLEAN NOT NULL
);

COMMIT;
